### ISSUE TITLE
Syslog is getting disabled

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/herky#17]
Since sitenow_syslog depends upon syslog, the syslog module is getting disabled. We should add to the drush recipe to enable syslog again

**Comment by richardbporter** [comment]
That explains why I wasn't seeing log messages...

**Comment by brandonneil** [comment]
Might as well add an extra disable for dblog as well when we're updating this.

**Comment by brandonneil** [comment]
I've noticed that this is only happening sometimes. The INRC migration I'm currently running still has the syslog module enabled, after the migration steps.

**Comment by brandonneil** [comment]
I think only one of my migrations had it disabled. We should/could probably take care of this by making sure it's on as a dependency in both profiles, and enable it for the sites that it is not already enabled.
