### ISSUE TITLE
Decide localize functionality

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/herky#31]
There are 4 environment cases in the localize command: local, dev, test and prod. Each case is outlined starting on https://github.com/ITS-UofIowa/herky/blob/issue-31/herky.drush.inc#L655

**Comment by joewhitsitt** [comment]
These look fine to me as long as we clean up features/modules that have some of these as dependencies. Searching our organization, these appear to be the modules affected for views_ui, field_ui:

Profile code shouldn't matter and I don't think any module that isn't enabled matters either. Right? (e.g. engineering_development)

[views_ui](https://github.com/search?utf8=%E2%9C%93&q=org%3AITS-UofIowa+%22dependencies%5B%5D+%3D+views_ui%22&type=Code)

[field_ui](https://github.com/search?utf8=%E2%9C%93&q=org%3AITS-UofIowa+%22dependencies%5B%5D+%3D+field_ui%22&type=Code)

Thanks for the opt-out option!
